# Generated by Django 4.2.1 on 2023-05-23 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=255, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=255, null=True), size=None),
        ),
    ]
