# Generated by Django 4.2.1 on 2023-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0005_remove_profile_followingtweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followingtweet',
            field=models.JSONField(default=list),
        ),
    ]
