# Generated by Django 4.2.1 on 2023-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0008_alter_profile_followingtweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='C:/Users/DELL/Desktop/django-postgres/twitter/static/twitterlogo.png', upload_to='images/'),
        ),
    ]
