# Generated by Django 4.2.1 on 2023-05-30 15:10

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0017_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, default=datetime.datetime.now), default=list, size=None),
            preserve_default=False,
        ),
    ]
