# Generated by Django 4.2.1 on 2023-05-30 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0019_alter_profile_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
        migrations.AddField(
            model_name='profile',
            name='dt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
    ]
