# Generated by Django 4.2.1 on 2023-05-30 15:23

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0020_remove_profile_time_profile_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=datetime.datetime.now), default=list, size=None),
        ),
    ]
