# Generated by Django 4.2.1 on 2023-05-30 15:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0022_alter_profile_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, default=django.utils.timezone.now), default=list, size=None),
        ),
    ]
