# Generated by Django 4.2.1 on 2023-05-30 16:14

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0025_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tweet_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, verbose_name=datetime.datetime.now), default=list, size=None),
        ),
    ]
